IMAGE_FILES = <<~FILES.split
  img/1-introduction/()=0.es.png
  img/1-introduction/(2xnumber)+1.es.png
  img/1-introduction/(5+4)x3.es.png
  img/1-introduction/-7div-5reporting1.4.es.png
  img/1-introduction/-7div5reporting-1.4.es.png
  img/1-introduction/-7mod-5reporting-2.es.png
  img/1-introduction/-7mod5reporting3.es.png
  img/1-introduction/12-sided-figure-alternating-3-red-and-3-blue.es.png
  img/1-introduction/15-mod-5-reporting-0.es.png
  img/1-introduction/15-mod-5.es.png
  img/1-introduction/17-mod-5-reporting-2.es.png
  img/1-introduction/17-mod-5.es.png
  img/1-introduction/2-and-0.es.png
  img/1-introduction/2-plus-3.es.png
  img/1-introduction/360-divided-by-60.es.png
  img/1-introduction/360-divided-by-7.es.png
  img/1-introduction/3x3array-of-squares-on-stage.es.png
  img/1-introduction/4-squares-around-square.es.png
  img/1-introduction/5+(4x3)-reporting-17.es.png
  img/1-introduction/5+7.es.png
  img/1-introduction/5-by-5-superimposed-on-3-by-3.es.png
  img/1-introduction/5-squares-in-row-script.es.png
  img/1-introduction/5-squares-in-row.es.png
  img/1-introduction/5pt-and-7pt-stars-and-rectangle-blue.es.png
  img/1-introduction/5x5array-of-squares-on-stage.es.png
  img/1-introduction/6-sided-figure-alternating-red-and-blue.es.png
  img/1-introduction/7-branch-asterisk.es.png
  img/1-introduction/7-plus-3-equals-12-OR-7-plus-3-less-than-12-reports-true_548x44.es.png
  img/1-introduction/7-stars.es.png
  img/1-introduction/75-equals-435-mod-360-reporting.es.png
  img/1-introduction/7lt3-reporting-false.es.png
  img/1-introduction/7lt3.es.png
  img/1-introduction/7mod-5reporting-3.es.png
  img/1-introduction/7mod5reporting2.es.png
  img/1-introduction/8-sided-figure-alternating-red-and-blue.es.png
  img/1-introduction/BuggyBackward.es.png
  img/1-introduction/File-menu-import-library.es.png
  img/1-introduction/Mystery-block.es.png
  img/1-introduction/Provide-getters-and-setters.es.png
  img/1-introduction/Script-tab.es.png
  img/1-introduction/SudokuBoard.es.png
  img/1-introduction/Tic-tac-toe-O.es.png
  img/1-introduction/Tic-tac-toe-X.es.png
  img/1-introduction/alonzo-code-too-fast.es.png
  img/1-introduction/alonzodance.es.png
  img/1-introduction/alphie-small.es.png
  img/1-introduction/angle.es.png
  img/1-introduction/ariel.es.png
  img/1-introduction/asterisk-result.es.png
  img/1-introduction/asterisk.es.png
  img/1-introduction/aww-snap-forever.es.png
  img/1-introduction/block-editor-with-pinwheel.es.png
  img/1-introduction/blue-triangle-embedded-between-move-and-turn-in-red-triangle.es.png
  img/1-introduction/board-var.es.png
  img/1-introduction/brazil-flag.es.png
  img/1-introduction/broadcast-your-turn.es.png
  img/1-introduction/brown.es.png
  img/1-introduction/buggy-squiral-script.es.png
  img/1-introduction/buggyspell.es.png
  img/1-introduction/calculate-tile-size.es.png
  img/1-introduction/change-ghost-effect-input-numbers.es.png
  img/1-introduction/change-sprite-size.es.png
  img/1-introduction/chase-attractor.es.png
  img/1-introduction/chase-script.es.png
  img/1-introduction/choosing-Alonzo.es.png
  img/1-introduction/circle-script.es.png
  img/1-introduction/circle-squared-script.es.png
  img/1-introduction/circle-squared.es.png
  img/1-introduction/circle.es.png
  img/1-introduction/click-alonzo-script.es.png
  img/1-introduction/color-asterisk.es.png
  img/1-introduction/comment-as-help.es.png
  img/1-introduction/comment-in-editor.es.png
  img/1-introduction/composition.es.png
  img/1-introduction/cones-design.es.png
  img/1-introduction/count-by-10-from-100-to-0.es.png
  img/1-introduction/count-by-2-from-0-to-30.es.png
  img/1-introduction/count-to-10.es.png
  img/1-introduction/count-to-num.es.png
  img/1-introduction/count-up-num.es.png
  img/1-introduction/dbg-moving-forever.es.png
  img/1-introduction/dbg-pentagon.es.png
  img/1-introduction/design-inspired-by-Albers.es.png
  img/1-introduction/design-inspired-by-Albers2.es.png
  img/1-introduction/design-inspired-by-van-Doesburg.es.png
  img/1-introduction/direction-reporter-watcher.es.png
  img/1-introduction/draw-gameboard-with-3-tiles.es.png
  img/1-introduction/draw-gameboard-with-5-tiles.es.png
  img/1-introduction/draw-gameboard.es.png
  img/1-introduction/draw-in-red-script.es.png
  img/1-introduction/draw-in-red.es.png
  img/1-introduction/draw-n-by-n-board.es.png
  img/1-introduction/draw-square-87.es.png
  img/1-introduction/draw-square-block-with-empty-input.es.png
  img/1-introduction/draw-square-board.es.png
  img/1-introduction/draw-square-definition.es.png
  img/1-introduction/draw-square-input-definition.es.png
  img/1-introduction/draw-square-petal-flower-6-50-parameters.es.png
  img/1-introduction/draw-square-petal-flower-empty-parameters.es.png
  img/1-introduction/draw-square.es.png
  img/1-introduction/duplicating-a-sprite.es.png
  img/1-introduction/edit-reporter.es.png
  img/1-introduction/effect.es.png
  img/1-introduction/effects-fade-out.es.png
  img/1-introduction/end-test.es.png
  img/1-introduction/equals-reporting-true_293x44.es.png
  img/1-introduction/favorite-food-list.es.png
  img/1-introduction/favorite-food.es.png
  img/1-introduction/filled-triple-empty.es.png
  img/1-introduction/filled-triple-equals-what.es.png
  img/1-introduction/filled-triple-example.es.png
  img/1-introduction/filled-wins.es.png
  img/1-introduction/find-winning-triples.es.png
  img/1-introduction/five-squares-in-row.es.png
  img/1-introduction/floor(-7div-5)reporting1.es.png
  img/1-introduction/floor(-7div5)reporting2.es.png
  img/1-introduction/floor7div5reporting1.es.png
  img/1-introduction/for-say-letter-i-of-my-name-is-secret.es.png
  img/1-introduction/forever-2.es.png
  img/1-introduction/forever-4.es.png
  img/1-introduction/forever-go.es.png
  img/1-introduction/forever-skeleton.es.png
  img/1-introduction/full-screen-button.es.png
  img/1-introduction/g-r-block.es.png
  img/1-introduction/ghost-effect-alonzo.es.png
  img/1-introduction/ghost.es.png
  img/1-introduction/go-to-empty-inputs.es.png
  img/1-introduction/go-to-starting-place.es.png
  img/1-introduction/go-to-x-0-y-0_186x36.es.png
  img/1-introduction/gossip-insides.es.png
  img/1-introduction/gossip2.es.png
  img/1-introduction/gray-background-of-scripting-area.es.png
  img/1-introduction/greater.es.png
  img/1-introduction/greet-player-error.es.png
  img/1-introduction/greet-player-skeleton.es.png
  img/1-introduction/greet-player.es.png
  img/1-introduction/half-hex.es.png
  img/1-introduction/has-player-won.es.png
  img/1-introduction/if-1+1=3-say-yes-else-say-no.es.png
  img/1-introduction/ifbone.es.png
  img/1-introduction/import-tools.es.png
  img/1-introduction/input-variable.es.png
  img/1-introduction/intendedsquiral.es.png
  img/1-introduction/is-5-a-number-reporting-true.es.png
  img/1-introduction/is-triple-a-win.es.png
  img/1-introduction/item-random.es.png
  img/1-introduction/just-made-a-script-highlighted.es.png
  img/1-introduction/just-made-a-script.es.png
  img/1-introduction/just-reds.es.png
  img/1-introduction/keep-starts-e.es.png
  img/1-introduction/keep-xxx.es.png
  img/1-introduction/key-space-pressed-reporting-false.es.png
  img/1-introduction/knownpeople.es.png
  img/1-introduction/letter-1-of-world-reporting-w.es.png
  img/1-introduction/list-cat-dog-frog-rabbit.es.png
  img/1-introduction/login-menu.es.png
  img/1-introduction/logout-menu.es.png
  img/1-introduction/loops-sound-dialogue-01.es.png
  img/1-introduction/loops-sound-dialogue-02.es.png
  img/1-introduction/loops-sound-dialogue-03.es.png
  img/1-introduction/loops-sound-dialogue-04.es.png
  img/1-introduction/loops-sound-dialogue-05.es.png
  img/1-introduction/loops-sound-dialogue-06.es.png
  img/1-introduction/loops-sound-dialogue-07.es.png
  img/1-introduction/make-a-block-menu.es.png
  img/1-introduction/make-a-reporter.es.png
  img/1-introduction/make-a-variable.es.png
  img/1-introduction/make-draw-square-block.es.png
  img/1-introduction/map-filled-triple.es.png
  img/1-introduction/map-over-456.es.png
  img/1-introduction/map.es.png
  img/1-introduction/maybe.es.png
  img/1-introduction/maze1.es.png
  img/1-introduction/messy-code.es.png
  img/1-introduction/mm-snapshot.es.png
  img/1-introduction/mod-2-experiments.es.png
  img/1-introduction/more-complicated-who-definition.es.png
  img/1-introduction/motion-palette-blue.es.png
  img/1-introduction/motion-palette-unclicked.es.png
  img/1-introduction/mouse-down-reporting-false.es.png
  img/1-introduction/mouse.es.png
  img/1-introduction/move--4-steps.es.png
  img/1-introduction/move-10-steps.es.png
  img/1-introduction/move-turn-design-01.es.png
  img/1-introduction/move-turn-design-02.es.png
  img/1-introduction/move-turn-design-03.es.png
  img/1-introduction/move-turn.es.png
  img/1-introduction/move100turnCCW90.es.png
  img/1-introduction/n-by-n-array-of-5-tiles-of-size-80.es.png
  img/1-introduction/n-mod-2=0.es.png
  img/1-introduction/nested-forevers.es.png
  img/1-introduction/new-sprite-chase-script.es.png
  img/1-introduction/nextbone.es.png
  img/1-introduction/non-pseudo.es.png
  img/1-introduction/nonagon-script.es.png
  img/1-introduction/not-seven-plus-three-equals-12-reports-true_361x44.es.png
  img/1-introduction/not-true-reports-false244x44.es.png
  img/1-introduction/okay-move.es.png
  img/1-introduction/operator-fytd-01.es.png
  img/1-introduction/operator-fytd-02.es.png
  img/1-introduction/operator-fytd-03.es.png
  img/1-introduction/operator-fytd-04.es.png
  img/1-introduction/operator-fytd-05.es.png
  img/1-introduction/operator-fytd-06.es.png
  img/1-introduction/operator-fytd-07.es.png
  img/1-introduction/operator-fytd-08.es.png
  img/1-introduction/operator-fytd-09.es.png
  img/1-introduction/operator-fytd-10.es.png
  img/1-introduction/organized-code.es.png
  img/1-introduction/painted-small.es.png
  img/1-introduction/pale-wait.es.png
  img/1-introduction/pause_button.es.png
  img/1-introduction/pen-down-draw-square-100.es.png
  img/1-introduction/pen-down-draw-square.es.png
  img/1-introduction/pen-down-goto-0,0-clear.es.png
  img/1-introduction/pen-up.es.png
  img/1-introduction/piano.es.png
  img/1-introduction/pick-random--10-to-20.es.png
  img/1-introduction/pick-random-1-to-10-reporting-2.es.png
  img/1-introduction/pinwheel-asterisk.es.png
  img/1-introduction/pinwheel-block-without-input.es.png
  img/1-introduction/pinwheel-circle.es.png
  img/1-introduction/pinwheel-hat.es.png
  img/1-introduction/pinwheel-polygon.es.png
  img/1-introduction/pinwheel.es.png
  img/1-introduction/play-note-pick-random-50-to-80-for-0.5-beats.es.png
  img/1-introduction/plus-sign.es.png
  img/1-introduction/point-in-direction-90_221x36.es.png
  img/1-introduction/point-in-direction.es.png
  img/1-introduction/polygon-result.es.png
  img/1-introduction/predicate-a-01.es.png
  img/1-introduction/predicate-a-02.es.png
  img/1-introduction/predicate-a-03.es.png
  img/1-introduction/predicate-a-04.es.png
  img/1-introduction/predicate-a-05.es.png
  img/1-introduction/predicate-a-06.es.png
  img/1-introduction/predicate-a-07.es.png
  img/1-introduction/predicate-a-08.es.png
  img/1-introduction/predicate-b-01.es.png
  img/1-introduction/predicate-b-02.es.png
  img/1-introduction/predicate-b-03.es.png
  img/1-introduction/pyramid-of-triangles.es.png
  img/1-introduction/random-greeting-script.es.png
  img/1-introduction/random-tempo.es.png
  img/1-introduction/random-twice.es.png
  img/1-introduction/red-and-blue.es.png
  img/1-introduction/rep4-move-turn.es.png
  img/1-introduction/repeat-play-random-note-5-times.es.png
  img/1-introduction/repeat2-for-1-5-to-3-say-letter-i-of-abcdefg-wait-half-second.es.png
  img/1-introduction/report-score-+1.es.png
  img/1-introduction/reset-block-clear-first.es.png
  img/1-introduction/round-3.14-reporting-3.es.png
  img/1-introduction/round-3.14.es.png
  img/1-introduction/row-houses.es.png
  img/1-introduction/row-of-5tiles.es.png
  img/1-introduction/row-of-triangles.es.png
  img/1-introduction/russian.es.png
  img/1-introduction/say-version-of-who.es.png
  img/1-introduction/say-x-mod-2-even-odd.es.png
  img/1-introduction/say-x-mod-2.es.png
  img/1-introduction/screen-size_button.es.png
  "img/1-introduction/scripts for blue and red squares.es.png"
  img/1-introduction/set-flag-flat-line-ends.es.png
  img/1-introduction/set-pen-color-(default-red)_183x36.es.png
  img/1-introduction/setangle.es.png
  img/1-introduction/setpc-num.es.png
  img/1-introduction/setpc-pick.es.png
  img/1-introduction/settings_button.es.png
  img/1-introduction/setup-pinwheel-80-5-60.es.png
  img/1-introduction/setup-pinwheel-80-6-20.es.png
  img/1-introduction/share-project.es.png
  img/1-introduction/size-reporting-100.es.png
  img/1-introduction/size-reporting-85.es.png
  img/1-introduction/snap-center-tabs.es.png
  img/1-introduction/snap-coord-grid.es.png
  img/1-introduction/snaplogo.es.png
  img/1-introduction/sound-sweep-back.es.png
  img/1-introduction/sound-sweep-forward.es.png
  img/1-introduction/sound-sweep-up.es.png
  img/1-introduction/spell-backwards.es.png
  img/1-introduction/spell-script.es.png
  img/1-introduction/sprite-2.es.png
  img/1-introduction/sprite-in-corral.es.png
  img/1-introduction/sprite.es.png
  img/1-introduction/sqrt-of-25-reporting-5.es.png
  img/1-introduction/square-alternating-red-and-blue.es.png
  img/1-introduction/square-fractal2.es.png
  img/1-introduction/square-in-square.es.png
  img/1-introduction/state-non-transparent-square.es.png
  img/1-introduction/sum-odds.es.png
  img/1-introduction/tabs.es.png
  img/1-introduction/tell-stage.es.png
  img/1-introduction/tempo-reporting-120.es.png
  img/1-introduction/they-kept-talking.es.png
  img/1-introduction/three-color-sierpinski.es.png
  img/1-introduction/three-hexagons.es.png
  img/1-introduction/tic-tac-toe.es.png
  img/1-introduction/toofast.es.png
  img/1-introduction/top-half-bottom-half.es.png
  img/1-introduction/transparency.es.png
  img/1-introduction/triangle-nested-script.es.png
  img/1-introduction/triangle-nested.es.png
  img/1-introduction/triangle-script.es.png
  img/1-introduction/triangle-sound-script.es.png
  img/1-introduction/triangle.es.png
  img/1-introduction/triple-win-false.es.png
  img/1-introduction/triple-win-true.es.png
  img/1-introduction/ttt-board-and-list.es.png
  img/1-introduction/ttt-board.es.png
  img/1-introduction/turn-180-degrees.es.png
  img/1-introduction/turn-90-degrees.es.png
  img/1-introduction/turn-right-15.es.png
  img/1-introduction/turn-right-90.es.png
  img/1-introduction/two-color-sierpinski-code.es.png
  img/1-introduction/two-sprites-gossiping-script.es.png
  img/1-introduction/unicorn-horns.es.png
  img/1-introduction/variables-assignment-01.es.png
  img/1-introduction/variables-assignment-02.es.png
  img/1-introduction/variables-assignment-03.es.png
  img/1-introduction/variables-assignment-04.es.png
  img/1-introduction/variables-assignment-05.es.png
  img/1-introduction/variables-assignment-06.es.png
  img/1-introduction/when-I-am-clicked-next-costume.es.png
  img/1-introduction/when-greenflag-say-gossip-broadcast-your-turn.es.png
  img/1-introduction/white-box.es.png
  img/1-introduction/who-reporting-senora.es.png
  img/1-introduction/who-reporting.es.png
  img/1-introduction/wins-all.es.png
  img/1-introduction/wins-reporter.es.png
  img/1-introduction/wins.es.png
  img/1-introduction/wrong-triangle.es.png
  img/1-introduction/x-position-reporting--79.es.png
  img/1-introduction/x=7-reporting-true.es.png
  img/1-introduction/xlt9orx=9.es.png
  img/1-introduction/xy-grid.es.png
  img/2-complexity/(list-of-items)-contains-(some-item)-predicate.es.png
  img/2-complexity/10lt7reporting-true.es.png
  img/2-complexity/17-mod-5-reporting-2.es.png
  img/2-complexity/2-to-the--5-reporting.es.png
  img/2-complexity/2-to-the-5-reporting.es.png
  img/2-complexity/227-divided-by-60.es.png
  img/2-complexity/3+7+2-mod-9-reporting-3.es.png
  img/2-complexity/3-arg-addition-block.es.png
  img/2-complexity/3-to-the--3-reporting.es.png
  img/2-complexity/3-to-the-3-reporting.es.png
  img/2-complexity/372-mod-9-reporting-3.es.png
  img/2-complexity/5lt7reporting-true.es.png
  img/2-complexity/9-copies.es.png
  img/2-complexity/90-divided-by-30.es.png
  img/2-complexity/HI.es.png
  img/2-complexity/Stage-nonrandom.es.png
  img/2-complexity/U2L1-Assessment-pic.es.png
  img/2-complexity/U2L1-Assessment.es.png
  img/2-complexity/U2L1p1TIFB-altsol.es.png
  img/2-complexity/U2L2-Assessment-A.es.png
  img/2-complexity/U2L2-Assessment-B.es.png
  img/2-complexity/U2L2-Assessment-C.es.png
  img/2-complexity/U2L2-Assessment-D.es.png
  img/2-complexity/U2L2-Assessment.es.png
  img/2-complexity/U2L4-Assessment.es.png
  img/2-complexity/a-greater-than-or-equal-to-b.es.png
  img/2-complexity/a-gt-7.es.png
  img/2-complexity/accessing-blocktran.es.png
  img/2-complexity/albers_circles.es.png
  img/2-complexity/all-but-first-letter-of_235x27.es.png
  img/2-complexity/all-but-last-letter-of-butterfly-(with-result)-338x40.es.png
  img/2-complexity/all-but-last-letter-of-butterfly-255x27.es.png
  img/2-complexity/answer-definition.es.png
  img/2-complexity/answer-from-item-3-of-csquiz.es.png
  img/2-complexity/answer-selector-notype.es.png
  img/2-complexity/answer-var.es.png
  img/2-complexity/apple.es.png
  img/2-complexity/assigning-element-to-element-blocktran.es.png
  img/2-complexity/assigning-element-to-element.es.png
  img/2-complexity/assigning-element-to-variable-blocktran.es.png
  img/2-complexity/assigning-element-to-variable.es.png
  img/2-complexity/assigning-variable-to-element-blocktran.es.png
  img/2-complexity/assigning-variable-to-element.es.png
  img/2-complexity/backgrounds.es.png
  img/2-complexity/better-digit-sum.es.png
  img/2-complexity/better-divisors.es.png
  img/2-complexity/better-factorial.es.png
  img/2-complexity/between-false.es.png
  img/2-complexity/between-true.es.png
  img/2-complexity/bicolor-hello.es.png
  img/2-complexity/block_editor-max-block.es.png
  img/2-complexity/blue-square-embedded-in-red-square.es.png
  img/2-complexity/bouncing-off-walls-135-degrees-510x284.es.png
  img/2-complexity/bouncing-off-walls-510x231.es.png
  img/2-complexity/buggy-sum-from-low-to-high.es.png
  img/2-complexity/can-a-triangle-be-made-using-these-three-lengths.es.png
  img/2-complexity/cascade-version.es.png
  img/2-complexity/ceilingapprox.es.png
  img/2-complexity/challenge_1.es.png
  img/2-complexity/challenge_2.es.png
  img/2-complexity/challenge_3.es.png
  img/2-complexity/challenge_4.es.png
  img/2-complexity/challenge_5.es.png
  img/2-complexity/challenge_6.es.png
  img/2-complexity/clobber.es.png
  img/2-complexity/coln.es.png
  img/2-complexity/colored-circles.es.png
  img/2-complexity/colored_ovals.es.png
  img/2-complexity/complete-drawing-of-letter-a.es.png
  img/2-complexity/composition-are-any-equal-reporting.es.png
  img/2-complexity/conjugate-verb-(spanish)-for-nosotros-comer.es.png
  img/2-complexity/conjugate-verb-(spanish)-for-yo-tocar.es.png
  img/2-complexity/cookie-factorial-bug.es.png
  img/2-complexity/costume-names.es.png
  img/2-complexity/costume-number.es.png
  img/2-complexity/curving-and-bouncing-off-walls-135-degrees-510x318.es.png
  img/2-complexity/decagon-mandala-ring-and-outline-of-letter-A.es.png
  img/2-complexity/dialogue-script_2-297x230.es.png
  img/2-complexity/dialogue-script_3-297x213.es.png
  img/2-complexity/dir-div-20-mod-2.es.png
  img/2-complexity/dir-to-apple-gt-135.es.png
  img/2-complexity/direction-mod-23=0.es.png
  img/2-complexity/direction-mod-30-equals-0.es.png
  img/2-complexity/direction-mod-30.es.png
  img/2-complexity/direction-mod-60-203x28.es.png
  img/2-complexity/direction-mod-60-equals-0.es.png
  img/2-complexity/direction-mod-blank=0.es.png
  img/2-complexity/direction-mod-blank=20.es.png
  img/2-complexity/dist-div-20-mod-2.es.png
  img/2-complexity/dist-gt-100.es.png
  img/2-complexity/dist-gt-dir-script.es.png
  img/2-complexity/dist-gt-dir.es.png
  img/2-complexity/distance-to-mouse-less-than-20.es.png
  img/2-complexity/div-100-mod-2-x=y.es.png
  img/2-complexity/div-100-mod-3-x=y.es.png
  img/2-complexity/divisibility-by-7-algorithm.es.png
  img/2-complexity/divisible-for-pipe.es.png
  img/2-complexity/divisors-12-reporting.es.png
  img/2-complexity/divisors-9-reporting.es.png
  img/2-complexity/divisors-of-30-table.es.png
  img/2-complexity/divisors-sets.es.png
  img/2-complexity/divisors-with-pipe.es.png
  img/2-complexity/divisors.es.png
  img/2-complexity/does-have-6-letters-and-letter-5-is-g.es.png
  img/2-complexity/draw-a-row.es.png
  img/2-complexity/draw-a-tile.es.png
  img/2-complexity/draw-brick-wall-tif.es.png
  img/2-complexity/draw-brick-wall.es.png
  img/2-complexity/draw-the-board.es.png
  img/2-complexity/drawShape.es.png
  img/2-complexity/e-from-points.es.png
  img/2-complexity/error-list-not-initialized.es.png
  img/2-complexity/evaluate-then-code-quiz-1.es.png
  img/2-complexity/evaluate-then-code-quiz-2.es.png
  img/2-complexity/evaluate-then-code-quiz-3.es.png
  img/2-complexity/evaluate-then-code-quiz-4.es.png
  img/2-complexity/evaluate-then-code-quiz-5.es.png
  img/2-complexity/even-block-definition-complex.es.png
  img/2-complexity/even-block-definition-simple.es.png
  img/2-complexity/even-predicate-make-block.es.png
  img/2-complexity/even-predicate.es.png
  img/2-complexity/example-for-each.es.png
  img/2-complexity/example-list-accessing-assignment.es.png
  img/2-complexity/example-list-accessing.es.png
  img/2-complexity/example-list.es.png
  img/2-complexity/example-set-result-to-5-say-result-set-result-to-result-x-2-say-result.es.png
  img/2-complexity/export-draw-shape-blocks.es.png
  img/2-complexity/f-of-2-7-3-reporting.es.png
  img/2-complexity/f-of-3-7-2-reporting.es.png
  img/2-complexity/f-of-x-y-z-definition.es.png
  img/2-complexity/factorial-block.es.png
  img/2-complexity/factorial-definition.es.png
  img/2-complexity/fill-script.es.png
  img/2-complexity/first-triangle-script.es.png
  img/2-complexity/fixing-factorial-definition-if-n=0-report-1.es.png
  img/2-complexity/flat-line-ends.es.png
  img/2-complexity/for-i=1-to-length-of-number.es.png
  img/2-complexity/forever-go-to-mouse-if-xpos-lt-0-pen-red-else-pen-green-315x217.es.png
  img/2-complexity/forever-if-direction-gt-180-and-lt-270-set-color-red-else-green-move-1-Turn-1.es.png
  img/2-complexity/forever-if-direction-mod-90=0-size-5-color-red-else-1-green-move-1-turn-left-1_325x318.es.png
  img/2-complexity/forever-if-direction=30or60-set-pen-size-10-set-color-blue-else-size-1-color-red-move-1-turn-1_465x318.es.png
  img/2-complexity/forever-snap-to-mouse-pointer.es.png
  img/2-complexity/generic-Boolean-expression.es.png
  img/2-complexity/generic-command-block.es.png
  img/2-complexity/generic-expression.es.png
  img/2-complexity/generic-instruction.es.png
  img/2-complexity/generic-predicate-block.es.png
  img/2-complexity/generic-reporter-block.es.png
  img/2-complexity/go-to-each-point.es.png
  img/2-complexity/go-to-mouse-x-mouse-y.es.png
  img/2-complexity/go-to-point(point)-empty-definition-with-list-type-input-named-point.es.png
  img/2-complexity/go-to-point-point.es.png
  img/2-complexity/guess-number.es.png
  img/2-complexity/hint-script.es.png
  img/2-complexity/humpty-dumpty-tenniel.es.png
  img/2-complexity/if-blocktran.es.png
  img/2-complexity/if-direction-gt-180-and-lt-270-pen-size-1-else-pen-size-5-494x345.es.png
  img/2-complexity/if-direction-gt-180-pen-size-1-else-pen-size-5-232x339.es.png
  img/2-complexity/if-direction-lt-90-pen-size-5-else-pen-size-1-224x250.es.png
  img/2-complexity/if-direction-mod-60=0-pen-size-5-else-pen-size-1-325x256.es.png
  img/2-complexity/if-either-sprite-touching-edge-or-space-key-pressed-499x97.es.png
  img/2-complexity/if-else-blocktran.es.png
  img/2-complexity/if-even-n.es.png
  img/2-complexity/if-n-is-even.es.png
  img/2-complexity/if-n-mod-2-equals-0.es.png
  img/2-complexity/if-x-position-lt-0-pen-color-red-else-pen-color-green.es.png
  img/2-complexity/if-x-turn.es.png
  img/2-complexity/iftrue.es.png
  img/2-complexity/imperfect-quiz.es.png
  img/2-complexity/import-tools-menu.es.png
  img/2-complexity/input-arrows.es.png
  img/2-complexity/input-variable-for-pinwheelbranches-commented.es.png
  img/2-complexity/input-variable-for-pinwheelbranches.es.png
  img/2-complexity/invert-script.es.png
  img/2-complexity/is-e-a-vowel-(with-correct-result)-231x44.es.png
  img/2-complexity/is-e-last-letter-elephant-reporting-false.es.png
  img/2-complexity/is-integer.es.png
  img/2-complexity/is-last-letter-of-word-definition.es.png
  img/2-complexity/is-letter-a-vowel-(v1)-658x156.es.png
  img/2-complexity/is-letter-a-vowel-(v2)-367x526.es.png
  img/2-complexity/is-letter-a-vowel-(v3)-436x109.es.png
  img/2-complexity/is-letter-a-vowel-(v4)-395x213.es.png
  img/2-complexity/is-letter-blank-of-blank.es.png
  img/2-complexity/is-m-a-vowel-(with-correct-result)-239x44.es.png
  img/2-complexity/is-n-a-number.es.png
  img/2-complexity/is-t-last-letter-august-reporting-true.es.png
  img/2-complexity/is-w-in-boston-reporting-false.es.png
  img/2-complexity/is-w-in-new-york-reporting-true.es.png
  img/2-complexity/isa-menu.es.png
  img/2-complexity/item-1-of-csquiz.es.png
  img/2-complexity/item-2-of-csquiz.es.png
  img/2-complexity/item-2-of-item-3-of-csquiz.es.png
  img/2-complexity/item-pick-random-1-to-7-of-list-I-you-he-she-etc_605x33.es.png
  img/2-complexity/item-qmqmqm.es.png
  img/2-complexity/item2of.es.png
  img/2-complexity/join-(t)-all-but-first-letter-of.es.png
  img/2-complexity/join-117x27.es.png
  img/2-complexity/join-boss-es-147x27.es.png
  img/2-complexity/join-how-are-you-185x27.es.png
  img/2-complexity/join-t-all-but-first-letter-of-when-343x33.es.png
  img/2-complexity/join-word-and-s-231x40.es.png
  img/2-complexity/keep-example-4-new.es.png
  img/2-complexity/keep-example-5-new.es.png
  img/2-complexity/keep-example-5.es.png
  img/2-complexity/keep-example-6-new-reporting.es.png
  img/2-complexity/keep-for-pipe.es.png
  img/2-complexity/last-letter-is-s-and-last-letter-is-x-617x40.es.png
  img/2-complexity/last-letter-is-s-or-last-letter-is-x-604x40.es.png
  img/2-complexity/last-letter-of-169x27.es.png
  img/2-complexity/last-letter-of-all-but-last-letter-of-brush-372x33.es.png
  img/2-complexity/left-plus-sign.es.png
  img/2-complexity/length-blocktran.es.png
  img/2-complexity/length-of-118x27.es.png
  img/2-complexity/length-of-how-are-you-191x27.es.png
  img/2-complexity/length-of-join-how-are-you-287x33.es.png
  img/2-complexity/length-of-mess-191x40.es.png
  img/2-complexity/length-of-word-butterfly-162x27.es.png
  img/2-complexity/letter-(length-of-horse)-of-elephant-357x40.es.png
  img/2-complexity/letter-2-of-butterflies-205x27.es.png
  img/2-complexity/letter-2-of-mess-222x40.es.png
  img/2-complexity/letter-7-of-fly-155x27.es.png
  img/2-complexity/letter-i-of-number.es.png
  img/2-complexity/letter-length-butterfly-into-butterflies-375x40.es.png
  img/2-complexity/letter-minus-2-of-fly-160x27.es.png
  img/2-complexity/letter-n-of-word-142x27.es.png
  img/2-complexity/letter-pick-random-1-10-of-butterfly_395x33.es.png
  img/2-complexity/letter-that-is-the-length-of-a-word-into-that-word-347x33.es.png
  img/2-complexity/letter-that-is-the-length-of-butterfly-into-the-word-butterflies-335x33.es.png
  img/2-complexity/list-456.es.png
  img/2-complexity/list-[a-e-i-o-u]-177x27.es.png
  img/2-complexity/list-[a-e-i-o-u]-contains-d-310x33.es.png
  img/2-complexity/list-[a-e-i-o-u]-contains-e-310x33.es.png
  img/2-complexity/list-[a-e-i-o-u]-contains-m-313x33.es.png
  img/2-complexity/list-[a-e-i-o-u]-with-result-330x127.es.png
  img/2-complexity/list-abcd-equals-list-badc-reporting-false.es.png
  img/2-complexity/list-block-right-arrow.es.png
  img/2-complexity/list-of-vowels-contains-randomly-picked-letter-of-pencil_666x39.es.png
  img/2-complexity/list-points-starter.es.png
  img/2-complexity/local-variable-created-by-for-block-commented.es.png
  img/2-complexity/local-variable-created-by-for-block.es.png
  img/2-complexity/love-bug.es.png
  img/2-complexity/make-a-predicate-block.es.png
  img/2-complexity/make-a-reporter-block.es.png
  img/2-complexity/map-ceiling-over-list.es.png
  img/2-complexity/map-floor-over-list.es.png
  img/2-complexity/map-plus2-over-list-reporting.es.png
  img/2-complexity/map-round-over-list.es.png
  img/2-complexity/max-3-arg-code.es.png
  img/2-complexity/max-3-arg.es.png
  img/2-complexity/max-of-3-4-reporting.es.png
  img/2-complexity/max-of-cat-dog-output.es.png
  img/2-complexity/max-of-true-and-10.es.png
  img/2-complexity/max.es.png
  img/2-complexity/max1-definition.es.png
  img/2-complexity/max1and2-of-x-and-y-reporter-with-if-or-if-else.es.png
  img/2-complexity/max2-definition.es.png
  img/2-complexity/max3-definition.es.png
  img/2-complexity/max3and4-of-x-and-y-command-with-if-or-if-else.es.png
  img/2-complexity/max4-definition.es.png
  img/2-complexity/maze-above.es.png
  img/2-complexity/missing-condition.es.png
  img/2-complexity/mm2.es.png
  img/2-complexity/mondrian-script.es.png
  img/2-complexity/move-to-tile.es.png
  img/2-complexity/my-costumes.es.png
  img/2-complexity/my-menu.es.png
  img/2-complexity/mystery-predicate.es.png
  img/2-complexity/mystery-script-1.es.png
  img/2-complexity/mystery-script-2.es.png
  img/2-complexity/mystery1-back-and-forth.es.png
  img/2-complexity/mystery2-back-and-forth-no-abs.es.png
  img/2-complexity/mystery3-dvd-player-screen-saver.es.png
  img/2-complexity/mystery4-crenellation.es.png
  img/2-complexity/n-factorial-symbol.es.png
  img/2-complexity/n-factorial.es.png
  img/2-complexity/n-mod-2=0-138x23.es.png
  img/2-complexity/nested-tri-call-no-color.es.png
  img/2-complexity/nestedTriangleApplied.es.png
  img/2-complexity/nestedTriangleHeader.es.png
  img/2-complexity/nestedTriangleRecursive.es.png
  img/2-complexity/new-for-each-point-script.es.png
  img/2-complexity/nonrandom.es.png
  img/2-complexity/not-draggable.es.png
  img/2-complexity/noun-list-for-testing-plural.es.png
  img/2-complexity/num-le-23.es.png
  img/2-complexity/number-guessing-game-definition.es.png
  img/2-complexity/number-line.es.png
  img/2-complexity/number-of-divisors-12-reporting.es.png
  img/2-complexity/number-of-divisors-9-reporting.es.png
  img/2-complexity/numberline.es.png
  img/2-complexity/numbers-from-1-to.es.png
  img/2-complexity/old_list-points-starter.es.png
  img/2-complexity/omposition-are-any-equal.es.png
  img/2-complexity/on-the-board-p.es.png
  img/2-complexity/parabola.es.png
  img/2-complexity/pick-random-1-to-10-reporting-2.es.png
  img/2-complexity/pick-random-1-to-10-reporting-9.es.png
  img/2-complexity/pinwheel-blocktran.es.png
  img/2-complexity/play-on-n-by-n-board.es.png
  img/2-complexity/plural-hat-block-and-first-line-only.es.png
  img/2-complexity/plural_h-bush-with-result.es.png
  img/2-complexity/plural_h-crash-with-result.es.png
  img/2-complexity/plural_h-crutch-with-result.es.png
  img/2-complexity/plural_h-moth-with-result.es.png
  img/2-complexity/plural_h-mouse-with-(wrong)result.es.png
  img/2-complexity/plural_h.es.png
  img/2-complexity/plural_y-mouse-with-(wrong)result.es.png
  img/2-complexity/plural_y-sky-with-result.es.png
  img/2-complexity/plural_y-tray-with-result.es.png
  img/2-complexity/plurals-1.es.png
  img/2-complexity/plurals-2.es.png
  img/2-complexity/plurals-3.es.png
  img/2-complexity/plurals-4a.es.png
  img/2-complexity/plurals-4b.es.png
  img/2-complexity/plurals-5.es.png
  img/2-complexity/point-list-for-A.es.png
  img/2-complexity/polygon-definition.es.png
  img/2-complexity/polygon-hat-block.es.png
  img/2-complexity/polygonCode.es.png
  img/2-complexity/postfix-factorial.es.png
  img/2-complexity/power-set-result-to-1-repeat-2-(set-result-to-result-times-5)-say-result.es.png
  img/2-complexity/predicate-even-number.es.png
  img/2-complexity/predicates-idea.es.png
  img/2-complexity/prim-types.es.png
  img/2-complexity/question-answer-constructor-notype.es.png
  img/2-complexity/question-answer-constructor.es.png
  img/2-complexity/question-definition.es.png
  img/2-complexity/question-selector-notype.es.png
  img/2-complexity/quiz-mod-1.es.png
  img/2-complexity/quiz-mod-2.es.png
  img/2-complexity/quiz-mod-3.es.png
  img/2-complexity/quiz-mod-4.es.png
  img/2-complexity/quiz-questions-constructor-definition.es.png
  img/2-complexity/quiz-questions-list.es.png
  img/2-complexity/raise-base-to-the-power-of-exponent.es.png
  img/2-complexity/raise-to-the-power-recursive-definition.es.png
  img/2-complexity/random-polygon-script-372x300.es.png
  img/2-complexity/remove-blocktran.es.png
  img/2-complexity/repeat-until-direction-equals-0-move-1-turn-ccw-1.es.png
  img/2-complexity/repeat-until-direction-equals-90-move-1-turn-cw-1-then-move-1-turn-1.es.png
  img/2-complexity/repeat-until-direction-equals-90-move-1-turn-cw-1.es.png
  img/2-complexity/repeat-until-x-pos-greater-than-20.es.png
  img/2-complexity/robot-quiz-image.es.png
  img/2-complexity/robot.es.png
  img/2-complexity/robot_small.es.png
  img/2-complexity/robot_small_right.es.png
  img/2-complexity/round-floor-ceiling-table.es.png
  img/2-complexity/row-with-ceiling.es.png
  img/2-complexity/row-with-floor.es.png
  img/2-complexity/run-these-steps.es.png
  img/2-complexity/say-(result)-for-2-secs.es.png
  img/2-complexity/say-(vowels)-for-2-secs-say(total-letters)-for-2-secs-say((join-words-(this-passage-is)(vowels-divided-by-total-letters)-percent-vowels.es.png
  img/2-complexity/say-which-cell.es.png
  img/2-complexity/say-which.es.png
  img/2-complexity/say1.es.png
  img/2-complexity/say2.es.png
  img/2-complexity/say3.es.png
  img/2-complexity/score-increment-blocktran.es.png
  img/2-complexity/score-variable-reporting-7.es.png
  img/2-complexity/score-variable-reporting-8.es.png
  img/2-complexity/script-for-U2L1-p2-n1-ask-direction-up-down-left-right-and-move.es.png
  img/2-complexity/script-for-U2L1-p2-n1-ask-direction-up-down-left-right-and-move_buggy.es.png
  img/2-complexity/script-for-U2L1-p2-n1-ask-direction-up-down-left-right-and-move_if-else_version.es.png
  img/2-complexity/script-variables-sides-script-variables-size.es.png
  img/2-complexity/script-variables-sides-size.es.png
  img/2-complexity/script-with-2-repeat-untils-and-mod.es.png
  img/2-complexity/second-buggy-sum-from-low-to-high.es.png
  img/2-complexity/secret-number-assignment-blocktran.es.png
  img/2-complexity/secret-number-check.es.png
  img/2-complexity/secret-number.es.png
  img/2-complexity/set-pen-color-to-color-selector.es.png
  img/2-complexity/set-pen-color-to-number.es.png
  img/2-complexity/set-pensize-50-move-0.1-steps.es.png
  img/2-complexity/set-pensize-50-move-100-steps.es.png
  img/2-complexity/set-player-list-to-empty-list.es.png
  img/2-complexity/shopping-list-indices.es.png
  img/2-complexity/shoppinglist-empty-list-assignment-blocktran.es.png
  img/2-complexity/shoppinglist-full-list-assignment-blocktran.es.png
  img/2-complexity/show-forever-say-which-cell.es.png
  img/2-complexity/sketch-of-letter-A.es.png
  img/2-complexity/snap-pietmondrian.es.png
  img/2-complexity/snap-pietmondrian2.es.png
  img/2-complexity/solution-U2L1-p2-clock-problem.es.png
  img/2-complexity/solution1_U2L1-p1-n2_gamal-script-for-nw-arc-red-rest-of-circle-green.es.png
  img/2-complexity/solution1_U2L1-p1-n2_partial-gamal-script-for-nw-arc-red-rest-of-circle-green.es.png
  img/2-complexity/solution1_U2L1-p1-n2_script-for-nw-arc-red-rest-of-circle-green.es.png
  img/2-complexity/sprite-asking-question-with-answer-box.es.png
  img/2-complexity/sqrt-of-120x28.es.png
  img/2-complexity/stage-button.es.png
  img/2-complexity/stamp.es.png
  img/2-complexity/stoplight-green.es.png
  img/2-complexity/stoplight-red.es.png
  img/2-complexity/stoplight-yellow.es.png
  img/2-complexity/structure-of-372-minus-sum-of-digits.es.png
  img/2-complexity/stuff-here.es.png
  img/2-complexity/sum-from-3to3.es.png
  img/2-complexity/sum-from3to7-170x27.es.png
  img/2-complexity/sum-fromatob-170x27.es.png
  img/2-complexity/sum-of-two-smallest-reporting.es.png
  img/2-complexity/sum-of-two-smallest.es.png
  img/2-complexity/sum-recursive-definition.es.png
  img/2-complexity/switch-X.es.png
  img/2-complexity/switch-turtle.es.png
  img/2-complexity/tableau-1-piet-mondrian.es.png
  img/2-complexity/three-articles.es.png
  img/2-complexity/three-color-stoplights.es.png
  img/2-complexity/three-point-seven-factorial.es.png
  img/2-complexity/three-tiles.es.png
  img/2-complexity/touching-edge-185x28.es.png
  img/2-complexity/transpose-example.es.png
  img/2-complexity/triangle-new.es.png
  img/2-complexity/triangle.es.png
  img/2-complexity/triangular-definition.es.png
  img/2-complexity/triangular-numbers.es.png
  img/2-complexity/ttt-drop-sprite-script.es.png
  img/2-complexity/turn-180-degrees-206x38.es.png
  img/2-complexity/twinkle-transposed.es.png
  img/2-complexity/twinkle.es.png
  img/2-complexity/twinkle2.es.png
  img/2-complexity/two-events.es.png
  img/2-complexity/unicode(89)as-letter.es.png
  img/2-complexity/unicode-of-y.es.png
  img/2-complexity/var-check.es.png
  img/2-complexity/vowel-definition.es.png
  img/2-complexity/vowel-letter(1)of.es.png
  img/2-complexity/vowel-remover-script.es.png
  img/2-complexity/wait-mouse-down.es.png
  img/2-complexity/wait-not-mouse-down.es.png
  img/2-complexity/weekday.es.png
  img/2-complexity/weekend.es.png
  img/2-complexity/whats-my-rule-270x68.es.png
  img/2-complexity/whats-my-rule-script-270x120.es.png
  img/2-complexity/which-cell(n)-full.es.png
  img/2-complexity/which-cell(n)-without-computation.es.png
  img/2-complexity/x+y+z-definition.es.png
  img/2-complexity/x+y-gt--100.es.png
  img/2-complexity/x+y-gt-100.es.png
  img/2-complexity/x+y-lt--100.es.png
  img/2-complexity/x+y-lt-100.es.png
  img/2-complexity/x-div-100-mod-10.es.png
  img/2-complexity/x-gt-100-script.es.png
  img/2-complexity/x-gt-100.es.png
  img/2-complexity/x-lt--100.es.png
  img/2-complexity/x-lt-100-and-y-gt-100.es.png
  img/2-complexity/x-lt-100-or-y-gt-100.es.png
  img/2-complexity/x-lt-100.es.png
  img/2-complexity/x-lt-y-script.es.png
  img/2-complexity/x-y-lt--100.es.png
  img/2-complexity/xcor.es.png
  img/2-complexity/xposition+150thendiv100.es.png
  img/2-complexity/xy-gt-0.es.png
  img/2-complexity/xy-lt-0.es.png
  img/2-complexity/y-gt--100.es.png
  img/2-complexity/y-gt-100.es.png
  img/2-complexity/y-gtr-x.es.png
  img/2-complexity/y-lt--100.es.png
  img/2-complexity/y-lt-100.es.png
  img/2-complexity/ycor.es.png
  img/3-lists/(n+2)3.es.png
  img/3-lists/1-factorial-divided-by-0-factorial.es.png
  img/3-lists/2-factorial-divided-by-1-factorial.es.png
  img/3-lists/3-factorial-divided-by-2-factorial.es.png
  img/3-lists/3-factorial-reporting.es.png
  img/3-lists/3n+2.es.png
  img/3-lists/3x+7.es.png
  img/3-lists/4-factorial-divided-by-3-factorial.es.png
  img/3-lists/4-factorial-reporting.es.png
  img/3-lists/5-factorial-reporting.es.png
  img/3-lists/525px-Public_key_encryption.es.png
  img/3-lists/536px-Public_key_shared_secret.es.png
  img/3-lists/6-factorial-reporting.es.png
  img/3-lists/7+8+1.es.png
  img/3-lists/A-B-C.es.png
  img/3-lists/A.es.png
  img/3-lists/A_attempt.es.png
  img/3-lists/A_foreach.es.png
  img/3-lists/Explaining-keep-items-1st-letter-is-u.es.png
  img/3-lists/Keep-items-such-that(item-1-of-()-equals-x)-from-Current-game.es.png
  img/3-lists/Keep-items-such-that(item-1-of-TicTacToe-wins)-contains(item-2-of())-from-Current.es.png
  img/3-lists/Keep-items-such-that(item-1-of-TicTacToe-wins)-contains(item-2-of())-from-etc.es.png
  img/3-lists/Keep-items-such-that(list(1-2-3))-contains(item-2-of())-from-Current-game.es.png
  img/3-lists/TTT-o.es.png
  img/3-lists/TTT-x.es.png
  img/3-lists/TicTacToe-wins.es.png
  img/3-lists/X-coord-of-item-1-of-A.es.png
  img/3-lists/acronym_BJC.es.png
  img/3-lists/acronym_NYC.es.png
  img/3-lists/acronym_TTY.es.png
  img/3-lists/acronym_TTYL.es.png
  img/3-lists/acronym_phrase.es.png
  img/3-lists/acronym_start.es.png
  img/3-lists/add-empty-test.es.png
  img/3-lists/add-ex-1.es.png
  img/3-lists/add-ex-2.es.png
  img/3-lists/add-ex-3.es.png
  img/3-lists/add-family-first-contact.es.png
  img/3-lists/add-framework.es.png
  img/3-lists/add-given-first-contact.es.png
  img/3-lists/add-head.es.png
  img/3-lists/add-hint.es.png
  img/3-lists/add-items-of.es.png
  img/3-lists/add-nums.es.png
  img/3-lists/add-recur-framework.es.png
  img/3-lists/address-selector-untyped.es.png
  img/3-lists/agesel.es.png
  img/3-lists/all-but-first.es.png
  img/3-lists/all_triples_1.es.png
  img/3-lists/all_triples_2.es.png
  img/3-lists/alphie-adt.es.png
  img/3-lists/alphie-no-adt.es.png
  img/3-lists/and-block.es.png
  img/3-lists/and.es.png
  img/3-lists/answer-to-question.es.png
  img/3-lists/ascii-chart.es.png
  img/3-lists/ask-address.es.png
  img/3-lists/ask-name-definition.es.png
  img/3-lists/average-of-list-reporting.es.png
  img/3-lists/average_grades.es.png
  img/3-lists/axolotl.es.png
  img/3-lists/baby-names-composition.es.png
  img/3-lists/baby-names-get.es.png
  img/3-lists/baby-names-map-split.es.png
  img/3-lists/baby-names-split.es.png
  img/3-lists/bad-recur-reporter.es.png
  img/3-lists/bh-iter-select-sort.es.png
  img/3-lists/bh-remdup.es.png
  img/3-lists/bh-selection-sort.es.png
  img/3-lists/bh-spell-word.es.png
  img/3-lists/book-constructor.es.png
  img/3-lists/brazil-list.es.png
  img/3-lists/call-pred.es.png
  img/3-lists/camera-metadata.es.png
  img/3-lists/capital_sentences.es.png
  img/3-lists/cell-number-from-move.es.png
  img/3-lists/check1length3c2.es.png
  img/3-lists/check1length3c3.es.png
  img/3-lists/check1length3c6.es.png
  img/3-lists/check2capsentencec1.es.png
  img/3-lists/check2capsentencec2.es.png
  img/3-lists/check2capsentencec3.es.png
  img/3-lists/check2isaNumc1.es.png
  img/3-lists/check2isaNumc2.es.png
  img/3-lists/check2isaNumc3.es.png
  img/3-lists/check2squares1c5.es.png
  img/3-lists/check2squares1c8.es.png
  img/3-lists/circle.es.png
  img/3-lists/circular.es.png
  img/3-lists/code.es.png
  img/3-lists/color-gasket.es.png
  img/3-lists/combine-block.es.png
  img/3-lists/combine-example-1.es.png
  img/3-lists/combine-example-2.es.png
  img/3-lists/combine-min.es.png
  img/3-lists/combine-minus.es.png
  img/3-lists/combine-plus.es.png
  img/3-lists/combine-simple-example-new.es.png
  img/3-lists/combine-times.es.png
  img/3-lists/combine_add_1234.es.png
  img/3-lists/combine_minus_345.es.png
  img/3-lists/combine_mult_7x10.es.png
  img/3-lists/combine_with.es.png
  img/3-lists/comp2.es.png
  img/3-lists/comp3.es.png
  img/3-lists/compare-play-note-1.es.png
  img/3-lists/compare-play-note-2.es.png
  img/3-lists/compare-play-note-3.es.png
  img/3-lists/compare-play-note-4.es.png
  img/3-lists/compare-play-note-5.es.png
  img/3-lists/complex-sentence.es.png
  img/3-lists/compose.es.png
  img/3-lists/constant-first-input.es.png
  img/3-lists/contact-constructor-name-typed.es.png
  img/3-lists/contact-constructor-with-name-constructor.es.png
  img/3-lists/contact-constructor.es.png
  img/3-lists/contact-list-button-add-contact.es.png
  img/3-lists/contact-list-button-clear-list.es.png
  img/3-lists/contact-list-button-delete-contact.es.png
  img/3-lists/contact-list-button-show-contact.es.png
  img/3-lists/contact-list-list-view-name-list.es.png
  img/3-lists/contact-list-untyped.es.png
  img/3-lists/contact-list-watcher.es.png
  img/3-lists/contact-list-with-name-and-address-types.es.png
  img/3-lists/contact-type-selector.es.png
  img/3-lists/contact-with-tag.es.png
  img/3-lists/contacts.es.png
  img/3-lists/contains.es.png
  img/3-lists/coordinate-list-for-A.es.png
  img/3-lists/coordinates.es.png
  img/3-lists/coordinates_for.es.png
  img/3-lists/coordinates_for1.es.png
  img/3-lists/coordinates_for_1.es.png
  img/3-lists/coordinates_foreach.es.png
  img/3-lists/coordinates_input.es.png
  img/3-lists/copies-of.es.png
  img/3-lists/copy-framework.es.png
  img/3-lists/copy-of-block.es.png
  img/3-lists/corner-1-of-rectangle-reporting.es.png
  img/3-lists/corner-2-of-rectangle-reporting.es.png
  img/3-lists/corner-reporting.es.png
  img/3-lists/count-empty-test.es.png
  img/3-lists/count-head.es.png
  img/3-lists/count-of.es.png
  img/3-lists/countdown(n)-iterative.es.png
  img/3-lists/countdown(n)-recursive.es.png
  img/3-lists/crypt_diagram.es.png
  img/3-lists/current-game-variable.es.png
  img/3-lists/current-move-constructor.es.png
  img/3-lists/current-year-minus-contact-birth-year.es.png
  img/3-lists/database.es.png
  img/3-lists/date-constructor-in-day-selector-reporting.es.png
  img/3-lists/deff.es.png
  img/3-lists/delete-block.es.png
  img/3-lists/difference.es.png
  img/3-lists/display-form-abraham-lincoln.es.png
  img/3-lists/display-form-definition.es.png
  img/3-lists/display-form-sun-yixian.es.png
  img/3-lists/display-name-object.es.png
  img/3-lists/distance-metric.es.png
  img/3-lists/double.es.png
  img/3-lists/draw_shape_A.es.png
  img/3-lists/draw_shape_block.es.png
  img/3-lists/dropdown-block.es.png
  img/3-lists/dropdown-item.es.png
  img/3-lists/dropdown-menu.es.png
  img/3-lists/dropdown-touching.es.png
  img/3-lists/empty-list-block.es.png
  img/3-lists/enter-new-contact.es.png
  img/3-lists/expand_output.es.png
  img/3-lists/factorial-definition-itterative.es.png
  img/3-lists/factorial-definition-recursive.es.png
  img/3-lists/factpict.es.png
  img/3-lists/family-first.es.png
  img/3-lists/family-name.es.png
  img/3-lists/for-each-item-of-list(Russia-Haiti-Japan-Brazil-Rwanda-VietNam)-say-item-for-1-secs.es.png
  img/3-lists/foreach-display-contact.es.png
  img/3-lists/foreach-say-name.es.png
  img/3-lists/fpict.es.png
  img/3-lists/fraction-of-list-of-lists-within-list-of-lists-extended.es.png
  img/3-lists/fraction-of-list-of-lists-within-list-of-lists.es.png
  img/3-lists/gasket.es.png
  img/3-lists/gcd-20-50-reporting.es.png
  img/3-lists/gcd-36-40-reporting.es.png
  img/3-lists/get-address.es.png
  img/3-lists/get-answer-to-question.es.png
  img/3-lists/get-beats-selector.es.png
  img/3-lists/get-name.es.png
  img/3-lists/get-new-contact.es.png
  img/3-lists/get-phone.es.png
  img/3-lists/get-pitch-selector.es.png
  img/3-lists/given-first-name-sorted-order.es.png
  img/3-lists/given-first.es.png
  img/3-lists/given-name.es.png
  img/3-lists/go-to-point-item-3-of-A.es.png
  img/3-lists/gps_badpic.es.png
  img/3-lists/gps_coords.es.png
  img/3-lists/grade-selector-reporting.es.png
  img/3-lists/gs1.es.png
  img/3-lists/gs10.es.png
  img/3-lists/gs11.es.png
  img/3-lists/gs12.es.png
  img/3-lists/gs13.es.png
  img/3-lists/gs13x.es.png
  img/3-lists/gs1a.es.png
  img/3-lists/gs1b.es.png
  img/3-lists/gs2.es.png
  img/3-lists/gs2item.es.png
  img/3-lists/gs2list.es.png
  img/3-lists/gs3.es.png
  img/3-lists/gs3add_in_list.es.png
  img/3-lists/gs3add_to_list.es.png
  img/3-lists/gs3map_add.es.png
  img/3-lists/gs4.es.png
  img/3-lists/gs4say_any.es.png
  img/3-lists/gs4say_each.es.png
  img/3-lists/gs4say_list.es.png
  img/3-lists/gs4say_random.es.png
  img/3-lists/gs5.es.png
  img/3-lists/gs5how_many.es.png
  img/3-lists/gs6.es.png
  img/3-lists/gs7.es.png
  img/3-lists/gs8.es.png
  img/3-lists/gs9.es.png
  img/3-lists/gs_length0.es.png
  img/3-lists/gs_length2.es.png
  img/3-lists/gs_length_allbutfirst.es.png
  img/3-lists/gs_length_blanks.es.png
  img/3-lists/gs_length_green.es.png
  img/3-lists/gs_length_red.es.png
  img/3-lists/gsprevpr.es.png
  img/3-lists/hide.es.png
  img/3-lists/icecream.es.png
  img/3-lists/increasing_block.es.png
  img/3-lists/increasing_false.es.png
  img/3-lists/increasing_true.es.png
  img/3-lists/increasing_truemistake.es.png
  img/3-lists/increasing_wrongscript.es.png
  img/3-lists/index-read-list.es.png
  img/3-lists/index-spell-word.es.png
  img/3-lists/initials-demo.es.png
  img/3-lists/initials-map.es.png
  img/3-lists/intersection-reporting.es.png
  img/3-lists/is-A-a-list.es.png
  img/3-lists/is10_10_10magic.es.png
  img/3-lists/is12_13_14magic.es.png
  img/3-lists/is17_16_21magic.es.png
  img/3-lists/is80_10_60magic.es.png
  img/3-lists/isa-menu.es.png
  img/3-lists/isamagicsquare_block.es.png
  img/3-lists/item()of-coordinates.es.png
  img/3-lists/item(2)of-coordinates.es.png
  img/3-lists/item-1-of-TicTacToe-wins.es.png
  img/3-lists/item-1-of-current-game.es.png
  img/3-lists/item-1-of-item-1-of-A.es.png
  img/3-lists/item-2-of-item-1-of-A.es.png
  img/3-lists/item-5-of-shoppinglist-reporting-bananas.es.png
  img/3-lists/item_last.es.png
  img/3-lists/join()s.es.png
  img/3-lists/join-words.es.png
  img/3-lists/join.es.png
  img/3-lists/join_elephant.es.png
  img/3-lists/join_two_blanks.es.png
  img/3-lists/join_words_two_blanks.es.png
  img/3-lists/joinwords_elephant.es.png
  img/3-lists/joinwords_wholelists.es.png
  img/3-lists/joinwords_wholelistsresult.es.png
  img/3-lists/justplayer.es.png
  img/3-lists/keep-example-1.es.png
  img/3-lists/keep-example-2.es.png
  img/3-lists/keep-example-3.es.png
  img/3-lists/keep-items-1st-letter-is-b.es.png
  img/3-lists/keep-items-1st-letter-is-u.es.png
  img/3-lists/keep-items-2nd-letter-is-u.es.png
  img/3-lists/keep-items-4th-letter-is-u-with-reported-result.es.png
  img/3-lists/keep-items-4th-letter-is-u.es.png
  img/3-lists/keep_block.es.png
  img/3-lists/keep_letter1equalsletterblank.es.png
  img/3-lists/keep_listofNum.es.png
  img/3-lists/keep_map.es.png
  img/3-lists/keep_map_combine.es.png
  img/3-lists/keep_vowelsfromstates.es.png
  img/3-lists/lambda.es.png
  img/3-lists/length_block.es.png
  img/3-lists/lessthan.es.png
  img/3-lists/lincoln.es.png
  img/3-lists/list-5-what.es.png
  img/3-lists/list-containing-Brazil-data.es.png
  img/3-lists/list-h-i.es.png
  img/3-lists/list-of-points-table.es.png
  img/3-lists/list-of-points.es.png
  img/3-lists/list456.es.png
  img/3-lists/list_block.es.png
  img/3-lists/list_input_slot.es.png
  img/3-lists/list_list_movie_allbutfirst.es.png
  img/3-lists/list_list_movie_item2.es.png
  img/3-lists/list_list_movie_item_item.es.png
  img/3-lists/list_list_movies.es.png
  img/3-lists/list_list_todo.es.png
  img/3-lists/list_list_world_capitals.es.png
  img/3-lists/list_list_world_item1_item2.es.png
  img/3-lists/list_list_world_item2_item1.es.png
  img/3-lists/list_list_world_length.es.png
  img/3-lists/listblockempty.es.png
  img/3-lists/listofnumbers.es.png
  img/3-lists/listpic.es.png
  img/3-lists/lookup_block.es.png
  img/3-lists/lookup_block_def.es.png
  img/3-lists/lookup_reporter.es.png
  img/3-lists/lookup_result.es.png
  img/3-lists/lookup_result1.es.png
  img/3-lists/magic_firsttriples.es.png
  img/3-lists/magic_predicate.es.png
  img/3-lists/magic_square.es.png
  img/3-lists/magic_square_positions.es.png
  img/3-lists/magic_start_triples.es.png
  img/3-lists/magic_triples_square.es.png
  img/3-lists/magicsquare.es.png
  img/3-lists/map(item-2-of-())-over-Keep-items-such-that(item-1-of-()-equals-x)-from-Current-game.es.png
  img/3-lists/map-cell-number-from-move()-over-current-game-contains-current-move.es.png
  img/3-lists/map-squares.es.png
  img/3-lists/map3x+7.es.png
  img/3-lists/map_3x+7overempty.es.png
  img/3-lists/map_add_1234.es.png
  img/3-lists/map_item1overcapitals.es.png
  img/3-lists/map_join2.es.png
  img/3-lists/map_join3.es.png
  img/3-lists/map_join_s.es.png
  img/3-lists/map_lastletter_map_join.es.png
  img/3-lists/map_letter1_map_join.es.png
  img/3-lists/map_mult_7x10.es.png
  img/3-lists/map_over207.es.png
  img/3-lists/map_plural.es.png
  img/3-lists/mapcoord.es.png
  img/3-lists/mapinfron.es.png
  img/3-lists/max-of-list-reporting.es.png
  img/3-lists/max.es.png
  img/3-lists/max_of.es.png
  img/3-lists/maximum.es.png
  img/3-lists/maxpict.es.png
  img/3-lists/maxpict1.es.png
  img/3-lists/min-of-list-reporting.es.png
  img/3-lists/min.es.png
  img/3-lists/minimum.es.png
  img/3-lists/musical-round.es.png
  img/3-lists/name-constructor-reporting.es.png
  img/3-lists/name-display-contact-result.es.png
  img/3-lists/name-display-result.es.png
  img/3-lists/name-display.es.png
  img/3-lists/name-from-number.es.png
  img/3-lists/name-given.es.png
  img/3-lists/name-selector-reporting.es.png
  img/3-lists/name-selector-untyped.es.png
  img/3-lists/name-sorted-block.es.png
  img/3-lists/name-sorted-defn.es.png
  img/3-lists/name-sorting-contact-result.es.png
  img/3-lists/name-sorting-result.es.png
  img/3-lists/name-sorting.es.png
  img/3-lists/name-type.es.png
  img/3-lists/nested-triangle-9.es.png
  img/3-lists/nested-triangle.es.png
  img/3-lists/newglide.es.png
  img/3-lists/note-constructor.es.png
  img/3-lists/note-selector-length.es.png
  img/3-lists/note-selector-pitch.es.png
  img/3-lists/nouns.es.png
  img/3-lists/numbers_list.es.png
  img/3-lists/oddfilt.es.png
  img/3-lists/option-context-menu.es.png
  img/3-lists/option-dialog.es.png
  img/3-lists/option-readonly.es.png
  img/3-lists/or-block.es.png
  img/3-lists/or.es.png
  img/3-lists/output445-730-1015.es.png
  img/3-lists/phone-number-of-conditional-with-list-reporters.es.png
  img/3-lists/phone-number-of.es.png
  img/3-lists/phone-number-script.es.png
  img/3-lists/phone-selector-untyped.es.png
  img/3-lists/play-chord-for-beats-empty.es.png
  img/3-lists/play-notes-transpose-egyptian-example.es.png
  img/3-lists/play-notes-transpose-twinkle-example.es.png
  img/3-lists/play-song-block.es.png
  img/3-lists/play-song-data-type.es.png
  img/3-lists/play-song-row-row-row.es.png
  img/3-lists/play-song-transpose-row-row-row-by-19.es.png
  img/3-lists/play-song.es.png
  img/3-lists/play-sound-sequence.es.png
  img/3-lists/player-from-move-selector.es.png
  img/3-lists/plsq.es.png
  img/3-lists/plus.es.png
  img/3-lists/point-list-for-A.es.png
  img/3-lists/point.es.png
  img/3-lists/product.es.png
  img/3-lists/quotient.es.png
  img/3-lists/rectangle-reporting.es.png
  img/3-lists/recur-command.es.png
  img/3-lists/recur-reporter.es.png
  img/3-lists/recursive-countdown.es.png
  img/3-lists/remove-example.es.png
  img/3-lists/remove-framework.es.png
  img/3-lists/remove.es.png
  img/3-lists/replace.es.png
  img/3-lists/report-stack.es.png
  img/3-lists/row-row-row-reporter.es.png
  img/3-lists/s-states.es.png
  img/3-lists/schedule.es.png
  img/3-lists/search-contacts-for-Alph-reporting.es.png
  img/3-lists/search-contacts-for.es.png
  img/3-lists/search-inside-contact-address-reporting.es.png
  img/3-lists/search-inside-contact-name-reporting.es.png
  img/3-lists/search-inside-contact-phone-reporting.es.png
  img/3-lists/select-first-contact.es.png
  img/3-lists/selectionresult.es.png
  img/3-lists/sentence.es.png
  img/3-lists/sentence_to_list.es.png
  img/3-lists/set-B-to-A.es.png
  img/3-lists/set-B-to-copy.es.png
  img/3-lists/set-contact-list-to-expression-with-get-blocks.es.png
  img/3-lists/set-current-game-empty.es.png
  img/3-lists/set-tempo-to-(240)-bpm.es.png
  img/3-lists/set-tempo-to-empty.es.png
  img/3-lists/set_words.es.png
  img/3-lists/shopping-list-button-add-item.es.png
  img/3-lists/shopping-list-button-clean-up-list.es.png
  img/3-lists/shopping-list-button-clear-list.es.png
  img/3-lists/shopping-list-button-delete-item.es.png
  img/3-lists/shopping-list-button-search.es.png
  img/3-lists/shoppinglist.es.png
  img/3-lists/show.es.png
  img/3-lists/simple-name.es.png
  img/3-lists/simple-sentence.es.png
  img/3-lists/smallest-item.es.png
  img/3-lists/sort-contact-list.es.png
  img/3-lists/sort-contacts.es.png
  img/3-lists/sort-framework.es.png
  img/3-lists/sort-using-less.es.png
  img/3-lists/sort-using.es.png
  img/3-lists/sprite-saying-too-many-decimal-places.es.png
  img/3-lists/sprite-saying-two-decimal-places.es.png
  img/3-lists/sq.es.png
  img/3-lists/square-checker-1.es.png
  img/3-lists/square-checker-2.es.png
  img/3-lists/square-checker-3.es.png
  img/3-lists/square-roots-definition-blocktran.es.png
  img/3-lists/square-roots-definition.es.png
  img/3-lists/square1.es.png
  img/3-lists/square2.es.png
  img/3-lists/square3.es.png
  img/3-lists/square3a.es.png
  img/3-lists/square4.es.png
  img/3-lists/square_12_13_14.es.png
  img/3-lists/square_3_2_1.es.png
  img/3-lists/squares-demo.es.png
  img/3-lists/squares-framework.es.png
  img/3-lists/states.es.png
  img/3-lists/status-of-all-board.es.png
  img/3-lists/student-record-constructor.es.png
  img/3-lists/substitute-letter-block.es.png
  img/3-lists/substitute-letter-block2.es.png
  img/3-lists/substitute-triple-block-output.es.png
  img/3-lists/substitute-triple-block-output2.es.png
  img/3-lists/sum-from-4-to-6-reporting.es.png
  img/3-lists/sum-of-list-reporting.es.png
  img/3-lists/sum.es.png
  img/3-lists/sumof-5.es.png
  img/3-lists/sumof-781.es.png
  img/3-lists/sumof-9827.es.png
  img/3-lists/sumof-combine.es.png
  img/3-lists/sumof-framework.es.png
  img/3-lists/swap-list-example.es.png
  img/3-lists/swap-var-empty.es.png
  img/3-lists/tic-tac-toe-board.es.png
  img/3-lists/times.es.png
  img/3-lists/too-many-decimal-places.es.png
  img/3-lists/track-changes.es.png
  img/3-lists/transient.es.png
  img/3-lists/transpose-by-and-play-example.es.png
  img/3-lists/transpose-by-and-play-twinkle-example.es.png
  img/3-lists/transpose-by-example.es.png
  img/3-lists/transpose-by.es.png
  img/3-lists/transpose-chord.es.png
  img/3-lists/transpose-definition.es.png
  img/3-lists/triangular-number-4-reporting.es.png
  img/3-lists/triangular-number-5-reporting.es.png
  img/3-lists/triangular-number-6-reporting.es.png
  img/3-lists/triangular-number-definition-itterative.es.png
  img/3-lists/triangular-number-definition-recursive.es.png
  img/3-lists/triple_report.es.png
  img/3-lists/triple_report_2.es.png
  img/3-lists/triples.es.png
  img/3-lists/ttt-position.es.png
  img/3-lists/ttt-sample-call.es.png
  img/3-lists/ttt-triples-converter-output.es.png
  img/3-lists/ttt-triples-converter.es.png
  img/3-lists/ttt-triples-example.es.png
  img/3-lists/ttt-wins.es.png
  img/3-lists/typed-name.es.png
  img/3-lists/unicode-map.es.png
  img/3-lists/unicode_65_as_letter.es.png
  img/3-lists/unicode_of_a.es.png
  img/3-lists/upto.es.png
  img/3-lists/verbs.es.png
  img/3-lists/visual_list.es.png
  img/3-lists/wheel.es.png
  img/3-lists/win456.es.png
  img/3-lists/winning-combinations.es.png
  img/3-lists/winning-combo-357.es.png
  img/3-lists/wordlists.es.png
  img/3-lists/x-1.es.png
  img/3-lists/x-coordinate.es.png
  img/3-lists/x-of-corner-reporting.es.png
  img/3-lists/xcoord.es.png
  img/3-lists/xygrid.es.png
  img/3-lists/y-coordinate.es.png
  img/3-lists/y-of-corner-reporting.es.png
  img/3-lists/ycoord.es.png
  img/3-lists/yearbook-record-datatype.es.png
  img/4-internet/0.2+0.4.es.png
  img/4-internet/200bang-fixnum.es.png
  img/4-internet/7.6+8.7.es.png
  img/4-internet/GPS-map.es.png
  img/4-internet/IP-suite.es.png
  img/4-internet/TCP.es.png
  img/4-internet/as-seen.es.png
  img/4-internet/astronaut.es.png
  img/4-internet/bang.es.png
  img/4-internet/bang10.es.png
  img/4-internet/bang20.es.png
  img/4-internet/bang30-bignum.es.png
  img/4-internet/bang30.es.png
  img/4-internet/bang5.es.png
  img/4-internet/baselinexy.es.png
  img/4-internet/bignums-true.es.png
  img/4-internet/boston62.es.png
  img/4-internet/citieslist.es.png
  img/4-internet/citiesreport.es.png
  img/4-internet/contains.es.png
  img/4-internet/coordinates-list-of-lists.es.png
  img/4-internet/current-temp-34.es.png
  img/4-internet/current-temp.es.png
  img/4-internet/current-weather-reporting.es.png
  img/4-internet/domain-name-reporting.es.png
  img/4-internet/duckduck-ip-address-fail.es.png
  img/4-internet/empty-result.es.png
  img/4-internet/encode-reporting.es.png
  img/4-internet/exponential.es.png
  img/4-internet/git.es.png
  img/4-internet/global-internet-use.es.png
  img/4-internet/gpslist.es.png
  img/4-internet/http-http.es.png
  img/4-internet/http-reporting.es.png
  img/4-internet/img_data_Inernet_API_Lab_Query_Sample.es.png
  img/4-internet/img_data_Inernet_API_Lab_Query_Temp.es.png
  img/4-internet/img_data_Internet_API_Lab_Listify_Sample.es.png
  img/4-internet/internet-transmit.es.png
  img/4-internet/intfoo.es.png
  img/4-internet/ipinfo-screenshot.es.png
  img/4-internet/ipv4.es.png
  img/4-internet/ipv6.es.png
  img/4-internet/jsfunc.es.png
  img/4-internet/libraries-dir-list.es.png
  img/4-internet/libraries-txt-list.es.png
  img/4-internet/libraries-txt.es.png
  img/4-internet/livestats-arrow.es.png
  img/4-internet/longshot.es.png
  img/4-internet/most-recent-version-snap.es.png
  img/4-internet/my-ip-addr.es.png
  img/4-internet/myFunction-hat-block.es.png
  img/4-internet/newyork60.es.png
  img/4-internet/obsolete.es.png
  img/4-internet/one-third.es.png
  img/4-internet/protein-folding.es.png
  img/4-internet/proxied-http-definition.es.png
  img/4-internet/proxied-http.es.png
  img/4-internet/proxiedcombo.es.png
  img/4-internet/public-key.es.png
  img/4-internet/read-internet-data.es.png
  img/4-internet/restored-stones.es.png
  img/4-internet/s-b-e-body-reporting.es.png
  img/4-internet/s-b-e-body.es.png
  img/4-internet/scrape.es.png
  img/4-internet/script-var-x-set-x-to.es.png
  img/4-internet/send-IP.es.png
  img/4-internet/set-coordinates-to-split-CSV.es.png
  img/4-internet/set-pen-color-RGB.es.png
  img/4-internet/setRGB.es.png
  img/4-internet/small-stones.es.png
  img/4-internet/snap-google.es.png
  img/4-internet/snap-version-hint.es.png
  img/4-internet/snowden.es.png
  img/4-internet/split-by-line.es.png
  img/4-internet/sprite-local.es.png
  img/4-internet/square.es.png
  img/4-internet/substring-after-reporting.es.png
  img/4-internet/substring-after.es.png
  img/4-internet/substring-before-reporting.es.png
  img/4-internet/substring-before.es.png
  img/4-internet/substring-starting-with-reporting.es.png
  img/4-internet/substring-starting.es.png
  img/4-internet/substring-up-to-reporting.es.png
  img/4-internet/substring-upto.es.png
  img/4-internet/sunsettime1.es.png
  img/4-internet/sunsettime2.es.png
  img/4-internet/tim-berners-lee.es.png
  img/4-internet/umbrella.es.png
  img/4-internet/umbrellatrue.es.png
  img/4-internet/var.es.png
  img/4-internet/varfoo.es.png
  img/4-internet/weather-list.es.png
  img/4-internet/weather-report-1-city.es.png
  img/4-internet/when-get-any.es.png
  img/4-internet/world-map.es.png
  img/4-internet/wst-bos.es.png
  img/4-internet/wst-nyc.es.png
  img/4-internet/youget.es.png
  img/4-internet/zero-div-zero-reporting-NaN.es.png
  img/5-algorithms/1000numbers.es.png
  img/5-algorithms/5.1.2-SpriteSays.es.png
  img/5-algorithms/5.1.2-saypositionofnumber.es.png
  img/5-algorithms/Block-and-input-name-editors-showing-reporter-type-input.es.png
  img/5-algorithms/Gr6-age-height-weight-gender-stats.es.png
  img/5-algorithms/Graph-function.es.png
  img/5-algorithms/GraphDatapoints.es.png
  img/5-algorithms/NextSpriteName.es.png
  img/5-algorithms/PercentageOfDerekByYear.es.png
  img/5-algorithms/PercentageOfDerekByYearGraphOnly.es.png
  img/5-algorithms/PercentageOfDerekByYearGraphOnly2.es.png
  img/5-algorithms/PlotPoint-simple.es.png
  img/5-algorithms/PlotPoint.es.png
  img/5-algorithms/Script-for-sprite-5.es.png
  img/5-algorithms/When-green-flag-clicked-initializer.es.png
  img/5-algorithms/algorithm-A.es.png
  img/5-algorithms/algorithm-B.es.png
  img/5-algorithms/alphieidea.es.png
  img/5-algorithms/alphiepict.es.png
  img/5-algorithms/announce-axes-position.es.png
  img/5-algorithms/are-numbers-in-list-distinct-reporting-true.es.png
  img/5-algorithms/are-numbers-in-list-distinct-reporting.es.png
  img/5-algorithms/average-time-alphie-way-500-10-reporting.es.png
  img/5-algorithms/avtime.es.png
  img/5-algorithms/awful-list-definition.es.png
  img/5-algorithms/awful-list-indexed.es.png
  img/5-algorithms/awful-list-indexed_old.es.png
  img/5-algorithms/babypic.es.png
  img/5-algorithms/best-empty-square.es.png
  img/5-algorithms/betsy-way-13-reporting-91.es.png
  img/5-algorithms/can-player-win-now.es.png
  img/5-algorithms/can-xo-win-now.es.png
  img/5-algorithms/capitals_watcher.es.png
  img/5-algorithms/car5flag.es.png
  img/5-algorithms/car5space.es.png
  img/5-algorithms/cars-list-view.es.png
  img/5-algorithms/cars-table-view.es.png
  img/5-algorithms/check-for-wins-and-ties-definition.es.png
  img/5-algorithms/check-for-wins-and-ties.es.png
  img/5-algorithms/combine-with(plus)items-of-list-from(1)through(13)-withResults.es.png
  img/5-algorithms/constant.es.png
  img/5-algorithms/correlation-negative.es.png
  img/5-algorithms/correlation-none.es.png
  img/5-algorithms/correlation-positive-trend.es.png
  img/5-algorithms/correlation-positive.es.png
  img/5-algorithms/costumeTooHigh.es.png
  img/5-algorithms/costumeTooLow.es.png
  img/5-algorithms/costumeYay.es.png
  img/5-algorithms/current-time.es.png
  img/5-algorithms/digitnumbers.es.png
  img/5-algorithms/distinctelements.es.png
  img/5-algorithms/dupdisplay.es.png
  img/5-algorithms/elisha-gray.es.png
  img/5-algorithms/emoji-happy.es.png
  img/5-algorithms/emoji-sad.es.png
  img/5-algorithms/find-first.es.png
  img/5-algorithms/function-((-5)-plus-(()-plus-(-3))-squared.es.png
  img/5-algorithms/go-to-scaled-point-x-y.es.png
  img/5-algorithms/graph-datapoints-DerekData1927to2015.es.png
  img/5-algorithms/graphdat.es.png
  img/5-algorithms/halts-tester-tester.es.png
  img/5-algorithms/how-many-x-in-x-5-x-reporting.es.png
  img/5-algorithms/just5.es.png
  img/5-algorithms/list-from(1)through(13)-withResults.es.png
  img/5-algorithms/list-from-1-to-7-reporting.es.png
  img/5-algorithms/list-from.es.png
  img/5-algorithms/listbetween.es.png
  img/5-algorithms/listbetween1116.es.png
  img/5-algorithms/listbetweenlist.es.png
  img/5-algorithms/listfrom.es.png
  img/5-algorithms/listtimes.es.png
  img/5-algorithms/loop-fn.es.png
  img/5-algorithms/make-list-of-times.es.png
  img/5-algorithms/make-player-move-definition.es.png
  img/5-algorithms/make-player-move.es.png
  img/5-algorithms/map-item-1-of-over-cars.es.png
  img/5-algorithms/mean(awful-list)-withResult.es.png
  img/5-algorithms/mean(awful-list)-withResult_old.es.png
  img/5-algorithms/median(awful-list)-withResult.es.png
  img/5-algorithms/metadata.es.png
  img/5-algorithms/meucci.es.png
  img/5-algorithms/next-move-for-computer-definition.es.png
  img/5-algorithms/next-move.es.png
  img/5-algorithms/number-of-in.es.png
  img/5-algorithms/numbers-from-to.es.png
  img/5-algorithms/opponent-to-o-reporting.es.png
  img/5-algorithms/opponent.es.png
  img/5-algorithms/orderedfinder.es.png
  img/5-algorithms/pick-a-move.es.png
  img/5-algorithms/plotblock.es.png
  img/5-algorithms/position-of-number-11-in-sorted-list-awful-list.es.png
  img/5-algorithms/position-of-number-2-in-sorted-list-awful-list.es.png
  img/5-algorithms/position-ranking.es.png
  img/5-algorithms/round-(input-number)-to-(n)-decimal-places.es.png
  img/5-algorithms/row-with-max-of-table-reporting.es.png
  img/5-algorithms/rundata.es.png
  img/5-algorithms/sayposition.es.png
  img/5-algorithms/stage-coord-for-x(1)-with-result.es.png
  img/5-algorithms/stage-coord-for-x-definition.es.png
  img/5-algorithms/stage-coord-for-x.es.png
  img/5-algorithms/stage-coord-for-y(165)-with-result.es.png
  img/5-algorithms/stage-coord-for-y.es.png
  img/5-algorithms/status-winning-triples.es.png
  img/5-algorithms/sum-from-1-to-13-reporting.es.png
  img/5-algorithms/sum-from-1-to-5-reporting.es.png
  img/5-algorithms/sum-from-1-to-8-reporting.es.png
  img/5-algorithms/sum-from-1-to-blank-expression.es.png
  img/5-algorithms/sum-of-definition.es.png
  img/5-algorithms/sum-of-list-from-1-to.es.png
  img/5-algorithms/three-fn.es.png
  img/5-algorithms/time-arrow.es.png
  img/5-algorithms/time-function-alphie-way-2000-reporting.es.png
  img/5-algorithms/time-function-betsy-way-2000-reporting.es.png
  img/5-algorithms/time-function-definition.es.png
  img/5-algorithms/time-function-list-between-1-1000-reporting.es.png
  img/5-algorithms/timereport.es.png
  img/5-algorithms/ttt-wins.es.png
  img/5-algorithms/unsorted-list.es.png
  img/5-algorithms/weird-fn.es.png
  img/5-algorithms/when-receive-any.es.png
  img/5-algorithms/winning-square-for-player-o-reporting.es.png
  img/5-algorithms/winning-square-for-player.es.png
  img/5-algorithms/winning-square-for.es.png
  img/5-algorithms/winning-triple-for-player-hint.es.png
  img/5-algorithms/winning-triple-for-player-reporting.es.png
  img/5-algorithms/winning-triple-for-player.es.png
  img/5-algorithms/wonp.es.png
  img/5-algorithms/words-list-sorted.es.png
  img/6-computers/(3-times-5)+4.es.png
  img/6-computers/200factorial.es.png
  img/6-computers/21factorial.es.png
  img/6-computers/22factorial.es.png
  img/6-computers/4-bit-adder.es.png
  img/6-computers/5-times-blank-plus-7.es.png
  img/6-computers/analog.es.png
  img/6-computers/apple-ii.es.png
  img/6-computers/binary-sequences-bug.es.png
  img/6-computers/bjc-logo-original-middle-row.es.png
  img/6-computers/bjc-logo-original.es.png
  img/6-computers/bjcfav.es.png
  img/6-computers/bjcfav_small.es.png
  img/6-computers/bjcfav_small_bw.es.png
  img/6-computers/church.es.png
  img/6-computers/computer-history-timeline.es.png
  img/6-computers/curve.es.png
  img/6-computers/digits-in-factorial-200.es.png
  img/6-computers/explore-api-example.es.png
  img/6-computers/exporting-output-watcher.es.png
  img/6-computers/factorial.es.png
  img/6-computers/fib(n)definition-rec.es.png
  img/6-computers/fib(n)definition.es.png
  img/6-computers/floats.es.png
  img/6-computers/heatsink.es.png
  img/6-computers/lengthoflog200factorial.es.png
  img/6-computers/leq.es.png
  img/6-computers/libraries-1.es.png
  img/6-computers/libraries-2.es.png
  img/6-computers/libraries-pen.es.png
  img/6-computers/log200factorial.es.png
  img/6-computers/logic-gate-xor.es.png
  img/6-computers/moore-exponential.es.png
  img/6-computers/moore.es.png
  img/6-computers/mooreslaw_graph.es.png
  img/6-computers/my-name.es.png
  img/6-computers/numberline0to1000.es.png
  img/6-computers/pond-small-palette.es.png
  img/6-computers/set-output-to-translate-text.es.png
  img/6-computers/timeline.es.png
  img/6-computers/top-row-of-pixels-in-bjc-logo.es.png
  img/6-computers/translate-binary-to-image.es.png
  img/6-computers/translate-binary-to-text.es.png
  img/6-computers/translate-text-to-binary.es.png
  img/6-computers/video-setting-vimeo.es.png
  img/6-computers/video-setting-youtube.es.png
  img/6-computers/video-setting.es.png
  img/6-computers/when-clicked-respond.es.png
  img/7-recursion/almost-beyond-mondrian.es.png
  img/7-recursion/beyond-mondrian.es.png
  img/7-recursion/example-projects.es.png
  img/7-recursion/factorial-reporter-definition.es.png
  img/7-recursion/forest.es.png
  img/7-recursion/fourtri.es.png
  img/7-recursion/greentree1.es.png
  img/7-recursion/greentree2.es.png
  img/7-recursion/greentree3.es.png
  img/7-recursion/greentree4.es.png
  img/7-recursion/greentree5.es.png
  img/7-recursion/greentree6.es.png
  img/7-recursion/greentree7.es.png
  img/7-recursion/greentree8.es.png
  img/7-recursion/greentree9.es.png
  img/7-recursion/koch-ish.es.png
  img/7-recursion/koch-ish2.es.png
  img/7-recursion/leafytree.es.png
  img/7-recursion/logic-inside-recursive-tree-v1.es.png
  img/7-recursion/logic-inside-recursive-tree-v2.es.png
  img/7-recursion/mondrian-block-definition-with-blanks.es.png
  img/7-recursion/random-tree-buggy-code-snap.es.png
  img/7-recursion/rectangle-header.es.png
  img/7-recursion/recursive-square.es.png
  img/7-recursion/snowflake-code-with-blanks.es.png
  img/7-recursion/tail-countdown.es.png
  img/7-recursion/tail-square.es.png
  img/7-recursion/thicktree.es.png
  img/7-recursion/tree-3.es.png
  img/7-recursion/tree-4.es.png
  img/7-recursion/tree-5.es.png
  img/7-recursion/tree-code-snap.es.png
  img/7-recursion/tree-header.es.png
  img/7-recursion/tree-level1.es.png
  img/7-recursion/tree-recursive(level)-size-(size)-alt.es.png
  img/7-recursion/tree-recursive-call.es.png
  img/7-recursion/tree-recursive-without-control.es.png
  img/7-recursion/tree-with-base-case.es.png
  img/7-recursion/tree-with-bent-trunk.es.png
  img/7-recursion/tree-with-five-branches.es.png
  img/7-recursion/tree.es.png
  img/7-recursion/tree2a.es.png
  img/7-recursion/tree3.es.png
  img/7-recursion/tree5.es.png
  img/7-recursion/treefail.es.png
  img/7-recursion/tri-frac-1-lev-3-in-4.es.png
  img/7-recursion/tri-frac-1-level-1.es.png
  img/7-recursion/tri-frac-1-level-2.es.png
  img/7-recursion/tri-frac-1-level-3.es.png
  img/7-recursion/tri-frac-1-level-4.es.png
  img/7-recursion/tri-frac-1-level-6.es.png
  img/7-recursion/tri-frac-2-level-2.es.png
  img/7-recursion/tri-frac-2-level-3.es.png
  img/7-recursion/tri-frac-2-level-8.es.png
  img/7-recursion/triangle-fractal-v2.es.png
  img/7-recursion/triangle-fractal-variation01.es.png
  img/7-recursion/triangle-fractal-variation02.es.png
  img/7-recursion/triangle-fractal-variation03.es.png
  img/7-recursion/vee-complex.es.png
  img/7-recursion/vee-complex2.es.png
  img/7-recursion/vee-simple.es.png
  img/8-recursive-reporters/2n+3.es.png
  img/8-recursive-reporters/abigailava.es.png
  img/8-recursive-reporters/appendblock.es.png
  img/8-recursive-reporters/bad-rec-reporter.es.png
  img/8-recursive-reporters/bfbf.es.png
  img/8-recursive-reporters/biglistnames.es.png
  img/8-recursive-reporters/bl.es.png
  img/8-recursive-reporters/committee.es.png
  img/8-recursive-reporters/committees.es.png
  img/8-recursive-reporters/common.es.png
  img/8-recursive-reporters/compare-time.es.png
  img/8-recursive-reporters/du-alonzo.es.png
  img/8-recursive-reporters/earliestin.es.png
  img/8-recursive-reporters/eightnames.es.png
  img/8-recursive-reporters/endse-ex.es.png
  img/8-recursive-reporters/evenitems.es.png
  img/8-recursive-reporters/evens.es.png
  img/8-recursive-reporters/ex-ex.es.png
  img/8-recursive-reporters/factorial.es.png
  img/8-recursive-reporters/hint.es.png
  img/8-recursive-reporters/iota.es.png
  img/8-recursive-reporters/keep-not-smallest.es.png
  img/8-recursive-reporters/letterblock.es.png
  img/8-recursive-reporters/list-to-sentence.es.png
  img/8-recursive-reporters/map-2n+3.es.png
  img/8-recursive-reporters/map-examples.es.png
  img/8-recursive-reporters/map-start.es.png
  img/8-recursive-reporters/mapinput.es.png
  img/8-recursive-reporters/mapmap.es.png
  img/8-recursive-reporters/mapsum-formal.es.png
  img/8-recursive-reporters/mapsum.es.png
  img/8-recursive-reporters/menu-example.es.png
  img/8-recursive-reporters/merge.es.png
  img/8-recursive-reporters/non-recursive-letter-count.es.png
  img/8-recursive-reporters/num-lessthan.es.png
  img/8-recursive-reporters/numbers-ex.es.png
  img/8-recursive-reporters/numbers-result.es.png
  img/8-recursive-reporters/pairup.es.png
  img/8-recursive-reporters/pascal-big-hint.es.png
  img/8-recursive-reporters/pascal-count.es.png
  img/8-recursive-reporters/pascal-framework.es.png
  img/8-recursive-reporters/pascal-rule.es.png
  img/8-recursive-reporters/pascal103.es.png
  img/8-recursive-reporters/pascal134.es.png
  img/8-recursive-reporters/pascal135.es.png
  img/8-recursive-reporters/pascal145.es.png
  img/8-recursive-reporters/pascal205.es.png
  img/8-recursive-reporters/piglatin.es.png
  img/8-recursive-reporters/q4a.es.png
  img/8-recursive-reporters/q4b.es.png
  img/8-recursive-reporters/q4c.es.png
  img/8-recursive-reporters/q4d.es.png
  img/8-recursive-reporters/r-to-l.es.png
  img/8-recursive-reporters/rangefrom.es.png
  img/8-recursive-reporters/rec-command.es.png
  img/8-recursive-reporters/rec-reporter.es.png
  img/8-recursive-reporters/recursive-letter-count.es.png
  img/8-recursive-reporters/reporter-type.es.png
  img/8-recursive-reporters/sasha.es.png
  img/8-recursive-reporters/say-B.es.png
  img/8-recursive-reporters/say-BJ.es.png
  img/8-recursive-reporters/say-BJC.es.png
  img/8-recursive-reporters/say-du-Alonzo.es.png
  img/8-recursive-reporters/say-du-bjc.es.png
  img/8-recursive-reporters/say-du.es.png
  img/8-recursive-reporters/sayeach.es.png
  img/8-recursive-reporters/selectionresult.es.png
  img/8-recursive-reporters/sort-ex.es.png
  img/8-recursive-reporters/sort.es.png
  img/8-recursive-reporters/sortednames.es.png
  img/8-recursive-reporters/sortlist.es.png
  img/8-recursive-reporters/sortusing.es.png
  img/8-recursive-reporters/squares-ex.es.png
  img/8-recursive-reporters/stringtogether.es.png
  img/8-recursive-reporters/subset-fast.es.png
  img/8-recursive-reporters/subset-slow.es.png
  img/8-recursive-reporters/subsets-framework.es.png
  img/8-recursive-reporters/tres-reportes.es.png
  img/8-recursive-reporters/u.es.png
  img/8-recursive-reporters/unsortednames.es.png
  img/8-recursive-reporters/unsortlist.es.png
  img/8-recursive-reporters/v.es.png
  img/8-recursive-reporters/w00zy.es.png
  img/8-recursive-reporters/x.es.png
  img/8-recursive-reporters/z.es.png
  img/abstraction/complicated-tic-tac-toe.es.png
  img/blocks/a-times-b.es.png
  img/blocks/abs-of-10.es.png
  img/blocks/abs.es.png
  img/blocks/all-but-last-letter-of.es.png
  img/blocks/answer-checked.es.png
  img/blocks/answer.es.png
  img/blocks/ceiling.es.png
  img/blocks/change-y.es.png
  img/blocks/change.es.png
  img/blocks/clear.es.png
  img/blocks/contains.es.png
  img/blocks/direction.es.png
  img/blocks/draw-square-empty-parameter.es.png
  img/blocks/equal.es.png
  img/blocks/equals.es.png
  img/blocks/floor.es.png
  img/blocks/follow-that-mouse-when-space.es.png
  img/blocks/for-blank.es.png
  img/blocks/for.es.png
  img/blocks/goto-mouse.es.png
  img/blocks/goto.es.png
  img/blocks/gtreq.es.png
  img/blocks/hide-variable-full-size.es.png
  img/blocks/hide.es.png
  img/blocks/i-greater-than-1.es.png
  img/blocks/if-else.es.png
  img/blocks/is-5-a-number.es.png
  img/blocks/is-a-number.es.png
  img/blocks/last-letter-of.es.png
  img/blocks/lesseq.es.png
  img/blocks/letter-blank-of-blank.es.png
  img/blocks/list.es.png
  img/blocks/max.es.png
  img/blocks/mod.es.png
  img/blocks/move-10-steps.es.png
  img/blocks/move-steps.es.png
  img/blocks/move.es.png
  img/blocks/not-sum-greater-2.es.png
  img/blocks/numbers-from-to.es.png
  img/blocks/obsolete.es.png
  img/blocks/pen-down.es.png
  img/blocks/pen-up.es.png
  img/blocks/pick-random-1-to-10.es.png
  img/blocks/pick-random-empty-args.es.png
  img/blocks/pipe.es.png
  img/blocks/plus-7-mouse-x.es.png
  img/blocks/repeat-empty.es.png
  img/blocks/reporter-if.es.png
  img/blocks/round-a-number.es.png
  img/blocks/say-Hello!-for-2-secs.es.png
  img/blocks/say-fragment.es.png
  img/blocks/scratch-cat-2.es.png
  img/blocks/scratch-cat.es.png
  img/blocks/sentence-to-list.es.png
  img/blocks/set-flat-line-ends.es.png
  img/blocks/set-pen-color-rgb.es.png
  img/blocks/set-pen-color-to-numeric.es.png
  img/blocks/set-pen-color-to-picker.es.png
  img/blocks/set-pen-color-to.es.png
  img/blocks/set-pen-color.es.png
  img/blocks/set-pen-size-to-1.es.png
  img/blocks/set-pen-size.es.png
  img/blocks/set-red.es.png
  img/blocks/set-video-with-menu.es.png
  img/blocks/set.es.png
  img/blocks/show-variable.es.png
  img/blocks/show.es.png
  img/blocks/size.es.png
  img/blocks/stamp.es.png
  img/blocks/stop-all.es.png
  img/blocks/sum-of-numbers-between-1-and-10.es.png
  img/blocks/tempo.es.png
  img/blocks/timer.es.png
  img/blocks/touching-color.es.png
  img/blocks/touching-sprite.es.png
  img/blocks/turn-CW-15-degrees.es.png
  img/blocks/turn-CW-degrees.es.png
  img/blocks/turn-left-180.es.png
  img/blocks/turn-left-90.es.png
  img/blocks/turn-left.es.png
  img/blocks/turn-right-90.es.png
  img/blocks/turn-right.es.png
  img/blocks/vertical-ellipsis.es.png
  img/blocks/warp.es.png
  img/blocks/when-I-am-dropped.es.png
  img/blocks/when-greenflag-clicked.es.png
  img/blocks/when-i-start-as-clone.es.png
  img/blocks/word-to-list.es.png
  img/blocks/x-position.es.png
  img/blocks/y-position.es.png
  img/icons/headphones-mini.png
  img/icons/import-tools-mini.png
  img/icons/new-project-mini.png
  img/icons/predict-mini.png
  img/icons/rotation-center.es.png
  img/icons/share-your-work-mini.png
  img/icons/teachers-choice-mini.png
  img/icons/teachers-choice.es.png
  img/icons/work-by-yourself-mini.png
  img/icons/work-with-a-partner-mini.png
  img/icons/write-in-journal-mini.png
  img/icons/write-out-thoughts-mini.png
FILES

puts IMAGE_FILES.length

ALL_FILES = Dir.glob('cur/**/*.html')
puts ALL_FILES.length

def escape(path)
  path.gsub('/', '\/')
end

def replace_content
  IMAGE_FILES.each do |path|
    es_path = escape(path)
    en_path = escape(path.gsub('.es.', '.'))
    ALL_FILES.each do |html|
      command = "perl -i -p -e 's/#{es_path}/#{en_path}/g;' #{html}"
      puts command
      `#{command}`
    end
  end
end

replace_content
