# frozen_string_literal: true

# This Gemfile is for tests inside this repo.
# The `build-tools` directory has its own Gemfile for the build tools.a

# Install with: bundle install --gemfile utilities/Gemfile
source 'https://rubygems.org'

ruby file: '.ruby-version'

gem 'axe-core-capybara'
gem 'axe-core-rspec'
gem 'capybara'
gem 'nokogiri'
gem 'rack-jekyll'
gem 'rspec'
gem 'selenium-webdriver'
gem 'webdrivers'
gem 'webrick'
