# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'fileutils'
gem 'nokogiri'
gem 'twitter_cldr'
gem 'i18n'

# https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-file
# https://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html
gem 'activesupport'

group :development do
  gem 'pry-byebug'
  gem 'rubocop'
end
