# frozen_string_literal: true

source 'https://rubygems.org'

ruby "~> 3.2"
# ruby '2.7.8'

gem 'fileutils'
gem 'nokogiri'
gem 'twitter_cldr'
gem 'i18n'

# https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-file
gem 'active_support'

## Development Utilties
gem 'rubocop'
